# Generated by Django 5.2.8 on 2025-11-29 00:39

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Egreso',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('razon', models.CharField(max_length=255)),
                ('costo', models.FloatField()),
                ('fecha', models.DateField(auto_now_add=True)),
                ('tipo_recurrencia', models.CharField(choices=[('unico', 'Único'), ('semanal', 'Semanal'), ('mensual', 'Mensual')], default='unico', max_length=10)),
                ('fecha_proximo_pago', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id_factura', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('monto_total', models.FloatField(default=0.0)),
                ('fecha_emision', models.DateTimeField(auto_now_add=True)),
                ('metodo_pago', models.CharField(default='Efectivo', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='FacturaProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('costo_unitario', models.FloatField()),
                ('cantidad', models.IntegerField(default=1)),
            ],
            options={
                'verbose_name': 'Producto Facturado',
                'verbose_name_plural': 'Productos Facturados',
            },
        ),
        migrations.CreateModel(
            name='FacturaServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('costo_unitario', models.FloatField()),
                ('cantidad', models.IntegerField(default=1)),
                ('porcentaje_comision', models.FloatField(default=0.0)),
                ('monto_comision', models.FloatField(default=0.0)),
            ],
            options={
                'verbose_name': 'Servicio Facturado',
                'verbose_name_plural': 'Servicios Facturados',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre_producto', models.CharField(max_length=150)),
                ('costo_compra', models.FloatField(default=0.0, verbose_name='Costo de Compra')),
                ('precio_venta', models.FloatField(default=0.0, verbose_name='Precio de Venta al Cliente')),
            ],
        ),
    ]
