# Generated by Django 5.2.8 on 2025-11-29 00:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agenda', '0002_initial'),
        ('finanzas', '0001_initial'),
        ('usuarios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='cliente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.cliente'),
        ),
        migrations.AddField(
            model_name='factura',
            name='recepcionista',
            field=models.ForeignKey(limit_choices_to={'rol': 'receptionist'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='facturaproducto',
            name='factura',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finanzas.factura'),
        ),
        migrations.AddField(
            model_name='facturaservicio',
            name='barbero',
            field=models.ForeignKey(limit_choices_to={'rol': 'barber'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='facturaservicio',
            name='factura',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finanzas.factura'),
        ),
        migrations.AddField(
            model_name='facturaservicio',
            name='servicio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='agenda.servicio'),
        ),
        migrations.AddField(
            model_name='facturaproducto',
            name='producto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='finanzas.producto'),
        ),
        migrations.AlterUniqueTogether(
            name='facturaservicio',
            unique_together={('factura', 'servicio', 'barbero')},
        ),
        migrations.AlterUniqueTogether(
            name='facturaproducto',
            unique_together={('factura', 'producto')},
        ),
    ]
