# Generated by Django 5.2.8 on 2025-12-01 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="client",
            options={"verbose_name": "clien", "verbose_name_plural": "clients"},
        ),
        migrations.AlterModelOptions(
            name="user",
            options={"verbose_name": "user", "verbose_name_plural": "users"},
        ),
        migrations.RenameField(
            model_name="client",
            old_name="location",
            new_name="address",
        ),
        migrations.RenameField(
            model_name="client",
            old_name="id_client",
            new_name="id",
        ),
        migrations.RenameField(
            model_name="client",
            old_name="lastname",
            new_name="last_name",
        ),
        migrations.RenameField(
            model_name="client",
            old_name="IDcedula",
            new_name="national_id",
        ),
        migrations.RenameField(
            model_name="client",
            old_name="phonenumber",
            new_name="phone_number",
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "Administrador"),
                    ("barber", "Barbero"),
                    ("receptionist", "Recepcionista"),
                ],
                default="barber",
                max_length=20,
                verbose_name="users roles",
            ),
        ),
    ]
