# Generated by Django 5.2.8 on 2025-12-01 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_client_options_alter_user_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="profile_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="users/profiles/",
                verbose_name="Foto de Perfil",
            ),
        ),
    ]
