# Generated by Django 5.2.8 on 2025-12-01 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_user_profile_image"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="client",
            options={"verbose_name": "client", "verbose_name_plural": "clients"},
        ),
    ]
