# Generated by Django 5.2.8 on 2025-12-01 03:31

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('bill_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total_amount', models.FloatField(default=0.0)),
                ('emision_date', models.DateTimeField(auto_now_add=True)),
                ('paiment_method', models.CharField(default='Efectivo', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='BillProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unitary_price', models.FloatField()),
                ('quantity', models.IntegerField(default=1)),
            ],
            options={
                'verbose_name': 'Producto Facturado',
                'verbose_name_plural': 'Productos Facturados',
            },
        ),
        migrations.CreateModel(
            name='BillServices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unitary_price', models.FloatField()),
                ('quantity', models.IntegerField(default=1)),
                ('commission_percentage', models.FloatField(default=0.0)),
                ('commission_ammount', models.FloatField(default=0.0)),
            ],
            options={
                'verbose_name': 'Servicio Facturado',
                'verbose_name_plural': 'Servicios Facturados',
            },
        ),
        migrations.CreateModel(
            name='Outflow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reazon', models.CharField(max_length=255)),
                ('price', models.FloatField()),
                ('date', models.DateField(auto_now_add=True)),
                ('frequency_date', models.CharField(choices=[('unico', 'Único'), ('semanal', 'Semanal'), ('mensual', 'Mensual')], default='unico', max_length=10)),
                ('next_payment_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id_product', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=150)),
                ('purchase_price', models.FloatField(default=0.0, verbose_name='Costo de Compra')),
                ('selling_price', models.FloatField(default=0.0, verbose_name='Precio de Venta al Cliente')),
            ],
        ),
    ]
