# Generated by Django 5.2.8 on 2025-12-01 03:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("finance", "0001_initial"),
        ("schedule", "0001_initial"),
        ("users", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="bill",
            name="client",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="users.client",
            ),
        ),
        migrations.AddField(
            model_name="bill",
            name="recepcionist",
            field=models.ForeignKey(
                limit_choices_to={"rol": "receptionist"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="billproduct",
            name="bill",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="finance.bill"
            ),
        ),
        migrations.AddField(
            model_name="billservices",
            name="barbero",
            field=models.ForeignKey(
                limit_choices_to={"rol": "barber"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="billservices",
            name="bill",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="finance.bill"
            ),
        ),
        migrations.AddField(
            model_name="billservices",
            name="service",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="schedule.services",
            ),
        ),
        migrations.AddField(
            model_name="billproduct",
            name="product",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="finance.product",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="billservices",
            unique_together={("bill", "service", "barbero")},
        ),
        migrations.AlterUniqueTogether(
            name="billproduct",
            unique_together={("bill", "product")},
        ),
    ]
