# Generated by Django 5.2.8 on 2025-12-01 03:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Finance', '0001_initial'),
        ('Schedule', '0001_initial'),
        ('Users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Users.client'),
        ),
        migrations.AddField(
            model_name='bill',
            name='recepcionist',
            field=models.ForeignKey(limit_choices_to={'rol': 'receptionist'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='billproduct',
            name='bill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Finance.bill'),
        ),
        migrations.AddField(
            model_name='billservices',
            name='barber',
            field=models.ForeignKey(limit_choices_to={'rol': 'barber'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='billservices',
            name='bill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Finance.bill'),
        ),
        migrations.AddField(
            model_name='billservices',
            name='service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Schedule.services'),
        ),
        migrations.AddField(
            model_name='billproduct',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Finance.product'),
        ),
        migrations.AlterUniqueTogether(
            name='billservices',
            unique_together={('bill', 'service', 'barber')},
        ),
        migrations.AlterUniqueTogether(
            name='billproduct',
            unique_together={('bill', 'product')},
        ),
    ]
