# Generated by Django 5.2.8 on 2025-12-01 03:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("schedule", "0001_initial"),
        ("users", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="barber",
            field=models.ForeignKey(
                limit_choices_to={"rol": "barber"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="appointment",
            name="client",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="users.client"
            ),
        ),
        migrations.AddField(
            model_name="barberservices",
            name="barber",
            field=models.ForeignKey(
                limit_choices_to={"rol": "barber"},
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Barbero",
            ),
        ),
        migrations.AddField(
            model_name="barberservices",
            name="service",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="schedule.services",
                verbose_name="Servicio",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="barberservices",
            unique_together={("barber", "service")},
        ),
    ]
