# Generated by Django 5.2.8 on 2025-11-29 00:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agenda', '0001_initial'),
        ('usuarios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='barberoservicio',
            name='barbero',
            field=models.ForeignKey(limit_choices_to={'rol': 'barber'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Barbero'),
        ),
        migrations.AddField(
            model_name='cita',
            name='barbero',
            field=models.ForeignKey(limit_choices_to={'rol': 'barber'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cita',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.cliente'),
        ),
        migrations.AddField(
            model_name='barberoservicio',
            name='servicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agenda.servicio', verbose_name='Servicio'),
        ),
        migrations.AlterUniqueTogether(
            name='barberoservicio',
            unique_together={('barbero', 'servicio')},
        ),
    ]
